declare module 'vue' {
  export interface GlobalComponents {
    SarAccordion: typeof import('./components/accordion/accordion.vue').default
    SarAccordionItem: typeof import('./components/accordion-item/accordion-item.vue').default
    SarActionSheet: typeof import('./components/action-sheet/action-sheet.vue').default
    SarAlert: typeof import('./components/alert/alert.vue').default
    SarAvatar: typeof import('./components/avatar/avatar.vue').default
    SarBackTop: typeof import('./components/back-top/back-top.vue').default
    SarBadge: typeof import('./components/badge/badge.vue').default
    SarButton: typeof import('./components/button/button.vue').default
    SarCalendar: typeof import('./components/calendar/calendar.vue').default
    SarCalendarInput: typeof import('./components/calendar-input/calendar-input.vue').default
    SarCard: typeof import('./components/card/card.vue').default
    SarCascader: typeof import('./components/cascader/cascader.vue').default
    SarCascaderInput: typeof import('./components/cascader-input/cascader-input.vue').default
    SarCheckbox: typeof import('./components/checkbox/checkbox.vue').default
    SarCheckboxGroup: typeof import('./components/checkbox-group/checkbox-group.vue').default
    SarCheckboxInput: typeof import('./components/checkbox-input/checkbox-input.vue').default
    SarCol: typeof import('./components/col/col.vue').default
    SarCollapse: typeof import('./components/collapse/collapse.vue').default
    SarCountDown: typeof import('./components/count-down/count-down.vue').default
    SarCountTo: typeof import('./components/count-to/count-to.vue').default
    SarDatetimePicker: typeof import('./components/datetime-picker/datetime-picker.vue').default
    SarDatetimePickerInput: typeof import('./components/datetime-picker-input/datetime-picker-input.vue').default
    SarDialog: typeof import('./components/dialog/dialog.vue').default
    SarDialogAgent: typeof import('./components/dialog-agent/dialog-agent.vue').default
    SarDropdown: typeof import('./components/dropdown/dropdown.vue').default
    SarDropdownItem: typeof import('./components/dropdown-item/dropdown-item.vue').default
    SarEmpty: typeof import('./components/empty/empty.vue').default
    SarFab: typeof import('./components/fab/fab.vue').default
    SarFloatingBubble: typeof import('./components/floating-bubble/floating-bubble.vue').default
    SarForm: typeof import('./components/form/form.vue').default
    SarFormItem: typeof import('./components/form-item/form-item.vue').default
    SarGrid: typeof import('./components/grid/grid.vue').default
    SarGridItem: typeof import('./components/grid-item/grid-item.vue').default
    SarIcon: typeof import('./components/icon/icon.vue').default
    SarIndexes: typeof import('./components/indexes/indexes.vue').default
    SarIndexesAnchor: typeof import('./components/indexes-anchor/indexes-anchor.vue').default
    SarInput: typeof import('./components/input/input.vue').default
    SarKeyboard: typeof import('./components/keyboard/keyboard.vue').default
    SarList: typeof import('./components/list/list.vue').default
    SarListItem: typeof import('./components/list-item/list-item.vue').default
    SarLoadMore: typeof import('./components/load-more/load-more.vue').default
    SarLoading: typeof import('./components/loading/loading.vue').default
    SarMarquee: typeof import('./components/marquee/marquee.vue').default
    SarMenu: typeof import('./components/menu/menu.vue').default
    SarNavbar: typeof import('./components/navbar/navbar.vue').default
    SarNavbarItem: typeof import('./components/navbar-item/navbar-item.vue').default
    SarNoticeBar: typeof import('./components/notice-bar/notice-bar.vue').default
    SarNotify: typeof import('./components/notify/notify.vue').default
    SarNotifyAgent: typeof import('./components/notify-agent/notify-agent.vue').default
    SarOverlay: typeof import('./components/overlay/overlay.vue').default
    SarPagination: typeof import('./components/pagination/pagination.vue').default
    SarPasswordInput: typeof import('./components/password-input/password-input.vue').default
    SarPicker: typeof import('./components/picker/picker.vue').default
    SarPickerInput: typeof import('./components/picker-input/picker-input.vue').default
    SarPopout: typeof import('./components/popout/popout.vue').default
    SarPopoutInput: typeof import('./components/popout-input/popout-input.vue').default
    SarPopover: typeof import('./components/popover/popover.vue').default
    SarPopoverReference: typeof import('./components/popover-reference/popover-reference.vue').default
    SarPopup: typeof import('./components/popup/popup.vue').default
    SarProgressBar: typeof import('./components/progress-bar/progress-bar.vue').default
    SarProgressCircle: typeof import('./components/progress-circle/progress-circle.vue').default
    SarPullDownRefresh: typeof import('./components/pull-down-refresh/pull-down-refresh.vue').default
    SarQrcode: typeof import('./components/qrcode/qrcode.vue').default
    SarRadio: typeof import('./components/radio/radio.vue').default
    SarRadioGroup: typeof import('./components/radio-group/radio-group.vue').default
    SarRadioInput: typeof import('./components/radio-input/radio-input.vue').default
    SarRate: typeof import('./components/rate/rate.vue').default
    SarResult: typeof import('./components/result/result.vue').default
    SarRow: typeof import('./components/row/row.vue').default
    SarSearch: typeof import('./components/search/search.vue').default
    SarShareSheet: typeof import('./components/share-sheet/share-sheet.vue').default
    SarSkeleton: typeof import('./components/skeleton/skeleton.vue').default
    SarSkeletonAvatar: typeof import('./components/skeleton-avatar/skeleton-avatar.vue').default
    SarSkeletonBlock: typeof import('./components/skeleton-block/skeleton-block.vue').default
    SarSkeletonParagraph: typeof import('./components/skeleton-paragraph/skeleton-paragraph.vue').default
    SarSkeletonTitle: typeof import('./components/skeleton-title/skeleton-title.vue').default
    SarSlider: typeof import('./components/slider/slider.vue').default
    SarStepper: typeof import('./components/stepper/stepper.vue').default
    SarSteps: typeof import('./components/steps/steps.vue').default
    SarSwiperDot: typeof import('./components/swiper-dot/swiper-dot.vue').default
    SarSwitch: typeof import('./components/switch/switch.vue').default
    SarTab: typeof import('./components/tab/tab.vue').default
    SarTabbar: typeof import('./components/tabbar/tabbar.vue').default
    SarTabbarItem: typeof import('./components/tabbar-item/tabbar-item.vue').default
    SarTable: typeof import('./components/table/table.vue').default
    SarTableRow: typeof import('./components/table-row/table-row.vue').default
    SarTableCell: typeof import('./components/table-cell/table-cell.vue').default
    SarTabs: typeof import('./components/tabs/tabs.vue').default
    SarTag: typeof import('./components/tag/tag.vue').default
    SarTimeline: typeof import('./components/timeline/timeline.vue').default
    SarTimelineItem: typeof import('./components/timeline-item/timeline-item.vue').default
    SarToast: typeof import('./components/toast/toast.vue').default
    SarToastAgent: typeof import('./components/toast-agent/toast-agent.vue').default
    SarTree: typeof import('./components/tree/tree.vue').default
    SarUpload: typeof import('./components/upload/upload.vue').default
  }
}

export {}
